### PR TITLE
Fixed/Added a few things!

### PR DESCRIPTION
**Pull request by JDOG787**
Hi there!

I added/fixed a lot of stuff here so let me tell you what I did. 

1. I fixed the problem of the list item number starting from zero. So this might be fixing some of issue #13 .
2. I fixed the remove command issue #34 .
3. I added the `addmany` command. Use `prefix+addmany item separated by a space` issue #26 .
4. I added the `removemany` command. Use `prefix+removemany <start index> <end index>` issue #27
5 I added commands 3 and 4 in the `help` command.

And thats it! If you have any questions let me know, thanks!

### CODE REVIEW

**Review by tomassirio — CHANGES_REQUESTED** [review]
The changes seem ok thus far. However, you need to pull the changes from the original fork on the master branch because i'm getting a lot of conflicts on the PR. Try to merge the master branch from the original fork first

**Comment by JDOG787** [comment]
@tomassirio hi sorry if I did something wrong i'm kind of new to GitHub so im still learning how it works. Im not sure what you are saying to do. Could you try explaining it again? thx

**Comment by tomassirio** [comment]
Sure, don't worry about it. We are all here to learn.

Right now you are working on a fork of my repository. This is different than just working on a cloned repository, you are working on your own ListBot right now. In order to get every modification from the original fork you will need to create a pull request on your own repository to merge my master branch (tomassirio/ListBot branch:master) to (JDOG787/ListBot branch:master). Thus every single update the original fork has got so far is going to be replicated on your fork as well.

After that you'll notice that your repository may get some conflicts that you'll need to resolve.

**Comment by JDOG787** [comment]
Ohhh ok! So if you merged my pull request right now you would lose the changes from other pull requests that were merged after I forked? Also ill look at what you said to do. Thanks!

**Comment by tomassirio** [comment]
If i merged right now i'd get a lot of errors on the original branch and every single person who is using the repository would get broken code which is a very bad practice

**Comment by JDOG787** [comment]
Hmmm ok. Im trying to figure out how to do what your saying.

**Comment by JDOG787** [comment]
Not sure how to make a pull request to my own repo. When I go to my repo and click make pull request it brings up this one. Any ideas? Sorry if this is a dumb question im just still learning.

**Pull request closed without merging**
