### PR TITLE
Hey there! Just fixed a couple of things I thought were needed.

### PR DESCRIPTION
**Pull request by Peiprjs**
Changed a bit the emoji integration and some error text. I'll continue working on it probably.

### CODE REVIEW

**Comment by Peiprjs** [comment]
It says there is an issue with README.md, just added my name

**Review by tomassirio — CHANGES_REQUESTED** [review]
Pull the new changes from the original repository since there's been a couple of updates here and there

**Comment by Peiprjs** [comment]
> Pull the new changes from the original repository since there's been a couple of updates here and there

Copy that, I'll also update and upgrade a couple of stuff I just found! Do you guys have a Discord server?

**Comment by tomassiriouala** [comment]
https://discord.gg/59YjSZ There is one now :D

**Pull request closed without merging**
