### PR TITLE
Add $promote command that can only be used by admin

### LINKED ISSUE #82: Add a command that only Admins can use $promote
The command should check if the user calling it is an Admin. It should receive as parameter a user (fe: $promote @tomassirio).

The person that adds ListBot to a server should be the first admin

### PR DESCRIPTION
**Pull request by ahmad-reza619**
This PR fix #82

### CODE REVIEW

**Comment by ahmad-reza619** [comment]
Hi there, i would like some confirmation, i have to store who is added the bot into the guild, where can i store that info though? in guild model, or do i need to add a new model called something like admin?

**Comment by tomassirio** [comment]
The guildCreate event should provide you with the info you need.

**Comment by tomassirio** [comment]
Great job @ahmad-reza619

**Comment by ahmad-reza619** [comment]
Thanks 😄

**Pull request merged**
